"""add_cascade_delete_to_transactions

Revision ID: 004
Revises: 003
Create Date: 2026-04-26 02:03:43.782588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vacation_period_transactions_period_id_fkey', 'vacation_period_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'vacation_period_transactions', 'vacation_periods', ['period_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacation_period_transactions', type_='foreignkey')
    op.create_foreign_key('vacation_period_transactions_period_id_fkey', 'vacation_period_transactions', 'vacation_periods', ['period_id'], ['id'])
    # ### end Alembic commands ###
