"""add_employee_id_to_users

Revision ID: 033
Revises: 032
Create Date: 2026-06-16 22:54:10.845742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033'
down_revision: Union[str, None] = '032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_doc_code_is_current'), table_name='documents')
    op.drop_index(op.f('ix_staffing_documents_is_current'), table_name='documents')
    op.create_index(op.f('ix_documents_doc_code'), 'documents', ['doc_code'], unique=False)
    op.create_index(op.f('ix_documents_is_current'), 'documents', ['is_current'], unique=False)
    op.drop_index(op.f('ix_notification_types_name'), table_name='notification_types')
    op.create_unique_constraint(None, 'notification_types', ['name'])
    op.drop_constraint(op.f('uq_order_employees_order_employee'), 'order_employees', type_='unique')
    op.create_index(op.f('ix_orders_employee_id'), 'orders', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_statement_types_name'), table_name='statement_types')
    op.create_unique_constraint(None, 'statement_types', ['name'])
    op.add_column('users', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(op.f('vacation_adjustments_vacation_id_fkey'), 'vacation_adjustments', type_='foreignkey')
    op.drop_constraint(op.f('vacation_adjustments_original_order_id_fkey'), 'vacation_adjustments', type_='foreignkey')
    op.drop_constraint(op.f('vacation_adjustments_adjustment_order_id_fkey'), 'vacation_adjustments', type_='foreignkey')
    op.create_foreign_key(None, 'vacation_adjustments', 'orders', ['original_order_id'], ['id'])
    op.create_foreign_key(None, 'vacation_adjustments', 'orders', ['adjustment_order_id'], ['id'])
    op.create_foreign_key(None, 'vacation_adjustments', 'vacations', ['vacation_id'], ['id'])
    op.drop_index(op.f('ix_vpt_adjustment_id'), table_name='vacation_period_transactions')
    op.drop_index(op.f('ix_vpt_adjustment_order_id'), table_name='vacation_period_transactions')
    op.drop_index(op.f('ix_vpt_manual_closure_id'), table_name='vacation_period_transactions')
    op.drop_index(op.f('ix_vpt_original_order_id'), table_name='vacation_period_transactions')
    op.create_index(op.f('ix_vacation_period_transactions_adjustment_id'), 'vacation_period_transactions', ['adjustment_id'], unique=False)
    op.create_index(op.f('ix_vacation_period_transactions_adjustment_order_id'), 'vacation_period_transactions', ['adjustment_order_id'], unique=False)
    op.create_index(op.f('ix_vacation_period_transactions_manual_closure_id'), 'vacation_period_transactions', ['manual_closure_id'], unique=False)
    op.create_index(op.f('ix_vacation_period_transactions_original_order_id'), 'vacation_period_transactions', ['original_order_id'], unique=False)
    op.drop_constraint(op.f('fk_vpt_original_order'), 'vacation_period_transactions', type_='foreignkey')
    op.drop_constraint(op.f('vacation_period_transactions_vacation_id_fkey'), 'vacation_period_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_vpt_adjustment_order'), 'vacation_period_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'vacation_period_transactions', 'vacations', ['vacation_id'], ['id'])
    op.create_foreign_key(None, 'vacation_period_transactions', 'orders', ['adjustment_order_id'], ['id'])
    op.create_foreign_key(None, 'vacation_period_transactions', 'orders', ['original_order_id'], ['id'])
    op.drop_constraint(op.f('fk_vacations_extension_order'), 'vacations', type_='foreignkey')
    op.drop_constraint(op.f('vacations_order_id_fkey'), 'vacations', type_='foreignkey')
    op.drop_constraint(op.f('fk_vacations_recall_order'), 'vacations', type_='foreignkey')
    op.drop_constraint(op.f('fk_vacations_postpone_order'), 'vacations', type_='foreignkey')
    op.create_foreign_key(None, 'vacations', 'orders', ['recall_order_id'], ['id'])
    op.create_foreign_key(None, 'vacations', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'vacations', 'orders', ['extension_order_id'], ['id'])
    op.create_foreign_key(None, 'vacations', 'orders', ['postpone_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacations', type_='foreignkey')
    op.drop_constraint(None, 'vacations', type_='foreignkey')
    op.drop_constraint(None, 'vacations', type_='foreignkey')
    op.drop_constraint(None, 'vacations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vacations_postpone_order'), 'vacations', 'orders', ['postpone_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vacations_recall_order'), 'vacations', 'orders', ['recall_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vacations_order_id_fkey'), 'vacations', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vacations_extension_order'), 'vacations', 'orders', ['extension_order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vacation_period_transactions', type_='foreignkey')
    op.drop_constraint(None, 'vacation_period_transactions', type_='foreignkey')
    op.drop_constraint(None, 'vacation_period_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vpt_adjustment_order'), 'vacation_period_transactions', 'orders', ['adjustment_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vacation_period_transactions_vacation_id_fkey'), 'vacation_period_transactions', 'vacations', ['vacation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vpt_original_order'), 'vacation_period_transactions', 'orders', ['original_order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vacation_period_transactions_original_order_id'), table_name='vacation_period_transactions')
    op.drop_index(op.f('ix_vacation_period_transactions_manual_closure_id'), table_name='vacation_period_transactions')
    op.drop_index(op.f('ix_vacation_period_transactions_adjustment_order_id'), table_name='vacation_period_transactions')
    op.drop_index(op.f('ix_vacation_period_transactions_adjustment_id'), table_name='vacation_period_transactions')
    op.create_index(op.f('ix_vpt_original_order_id'), 'vacation_period_transactions', ['original_order_id'], unique=False)
    op.create_index(op.f('ix_vpt_manual_closure_id'), 'vacation_period_transactions', ['manual_closure_id'], unique=False)
    op.create_index(op.f('ix_vpt_adjustment_order_id'), 'vacation_period_transactions', ['adjustment_order_id'], unique=False)
    op.create_index(op.f('ix_vpt_adjustment_id'), 'vacation_period_transactions', ['adjustment_id'], unique=False)
    op.drop_constraint(None, 'vacation_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'vacation_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'vacation_adjustments', type_='foreignkey')
    op.create_foreign_key(op.f('vacation_adjustments_adjustment_order_id_fkey'), 'vacation_adjustments', 'orders', ['adjustment_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vacation_adjustments_original_order_id_fkey'), 'vacation_adjustments', 'orders', ['original_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('vacation_adjustments_vacation_id_fkey'), 'vacation_adjustments', 'vacations', ['vacation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'employee_id')
    op.drop_constraint(None, 'statement_types', type_='unique')
    op.create_index(op.f('ix_statement_types_name'), 'statement_types', ['name'], unique=True)
    op.drop_index(op.f('ix_orders_employee_id'), table_name='orders')
    op.create_unique_constraint(op.f('uq_order_employees_order_employee'), 'order_employees', ['order_id', 'employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'notification_types', type_='unique')
    op.create_index(op.f('ix_notification_types_name'), 'notification_types', ['name'], unique=True)
    op.drop_index(op.f('ix_documents_is_current'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_code'), table_name='documents')
    op.create_index(op.f('ix_staffing_documents_is_current'), 'documents', ['is_current'], unique=False)
    op.create_index(op.f('ix_documents_doc_code_is_current'), 'documents', ['doc_code', 'is_current'], unique=False)
    # ### end Alembic commands ###
