"""add_order_days_map_to_vacation_periods

Revision ID: 952fc47895e1
Revises: 20260415_rename_days_count
Create Date: 2026-04-15 16:39:02.237205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '952fc47895e1'
down_revision: Union[str, None] = '20260415_rename_days_count'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_vacation_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_vacation_config_position'), 'position_vacation_config', ['position'], unique=True)
    op.create_table('references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_category'), 'references', ['category'], unique=False)
    op.drop_table('templates')
    op.create_foreign_key(None, 'departments', 'employees', ['head_employee_id'], ['id'])
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('holidays', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_constraint('holidays_date_key', 'holidays', type_='unique')
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.create_index(op.f('ix_orders_is_cancelled'), 'orders', ['is_cancelled'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('vacation_periods', sa.Column('order_days_map', sa.String(), nullable=True))
    op.drop_constraint('uq_vacation_plan_employee_year_month', 'vacation_plans', type_='unique')
    op.create_unique_constraint('uq_vacation_plan_emp_year_month', 'vacation_plans', ['employee_id', 'year', 'month'])
    op.drop_column('vacation_plans', 'days')
    op.create_index(op.f('ix_vacations_is_cancelled'), 'vacations', ['is_cancelled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacations_is_cancelled'), table_name='vacations')
    op.add_column('vacation_plans', sa.Column('days', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_constraint('uq_vacation_plan_emp_year_month', 'vacation_plans', type_='unique')
    op.create_unique_constraint('uq_vacation_plan_employee_year_month', 'vacation_plans', ['employee_id', 'year', 'month'])
    op.drop_column('vacation_periods', 'order_days_map')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_orders_is_cancelled'), table_name='orders')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.create_unique_constraint('holidays_date_key', 'holidays', ['date'])
    op.alter_column('holidays', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employees', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_content', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='templates_pkey')
    )
    op.drop_index(op.f('ix_references_category'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_position_vacation_config_position'), table_name='position_vacation_config')
    op.drop_table('position_vacation_config')
    # ### end Alembic commands ###
