"""add_letter_to_order_types

Revision ID: 9fb0d839a6df
Revises: f88501f31469
Create Date: 2026-04-26 23:32:31.958661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb0d839a6df'
down_revision: Union[str, None] = 'f88501f31469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_types', sa.Column('letter', sa.String(length=1), nullable=True))
    op.execute("""
        INSERT INTO order_types (code, name, is_active, show_in_orders_page, letter, field_schema)
        VALUES
            ('vacation_paid', 'Отпуск трудовой', true, false, 'л', '[]'),
            ('hire', 'Прием на работу', true, true, 'к', '[]'),
            ('dismissal', 'Увольнение', true, true, 'к', '[]'),
            ('transfer', 'Перевод', true, true, 'к', '[]'),
            ('contract_extension', 'Продление контракта', true, true, 'к', '[]'),
            ('vacation_unpaid', 'Отпуск за свой счет', true, false, 'к', '[]'),
            ('weekend_call', 'Вызов в выходной', true, false, 'к', '[]')
        ON CONFLICT (code) DO NOTHING;
    """)
    op.execute("""
        UPDATE order_types SET letter = 'л' WHERE code = 'vacation_paid';
    """)
    op.execute("""
        UPDATE order_types SET letter = 'к' WHERE code IN ('hire', 'dismissal', 'transfer', 'contract_extension', 'vacation_unpaid', 'weekend_call');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_types', 'letter')
    # ### end Alembic commands ###
