"""add_order_numbers_to_vacation_periods

Revision ID: a311cdf19df9
Revises: 952fc47895e1
Create Date: 2026-04-15 16:46:48.626755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a311cdf19df9'
down_revision: Union[str, None] = '952fc47895e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_periods', sa.Column('order_numbers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_periods', 'order_numbers')
    # ### end Alembic commands ###
