"""add_vacation_period_transactions

Revision ID: 0bfab6a26bb5
Revises: 0002_order_types
Create Date: 2026-04-26 00:38:29.765042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfab6a26bb5'
down_revision: Union[str, None] = '0002_order_types'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_period_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('vacation_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['vacation_periods.id'], ),
    sa.ForeignKeyConstraint(['vacation_id'], ['vacations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_period_transactions_period_id'), 'vacation_period_transactions', ['period_id'], unique=False)
    op.create_unique_constraint(None, 'order_types', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_types', type_='unique')
    op.drop_index(op.f('ix_vacation_period_transactions_period_id'), table_name='vacation_period_transactions')
    op.drop_table('vacation_period_transactions')
    # ### end Alembic commands ###
