"""add_remaining_days_to_vacation_periods

Revision ID: 36761822fac9
Revises: a311cdf19df9
Create Date: 2026-04-15 17:36:05.275384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36761822fac9'
down_revision: Union[str, None] = 'a311cdf19df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_periods', sa.Column('remaining_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_periods', 'remaining_days')
    # ### end Alembic commands ###
